maugli/conf/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import IndexView
from entries.views import EntriesView

urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include("store.urls")),
    url(r'^(?P<entry_link>news)/', EntriesView.as_view(), name="news"),
    url(r'^(?P<entry_link>\S+)/', include("entries.urls"), name="entry"),
]

maugli/entries/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import EntryView

app_name = "entries"
urlpatterns = [
    url(r'^$', EntryView.as_view()),
]

maugli/store/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import CatalogView

app_name = 'store'
urlpatterns = [
    url(r'^$', CatalogView.as_view(), name="catalog"),
]

maugli/entries/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from menu.models import MenuLink
class Entry(models.Model):
    class Meta:
        verbose_name_plural = "entries"
    ARTICLE = 'article'
    PAGE = 'page'
    TYPE_CHOICES = (
        (ARTICLE, 'Article'),
        (PAGE, 'Page'),
    )

    title = models.CharField(max_length=255)
    text  = models.TextField()
    type  = models.CharField(max_length=255, choices=TYPE_CHOICES,
                                default=ARTICLE)
    links = models.ManyToManyField(MenuLink, blank=True,
                                    related_name="entry")
    date  = models.DateField()

    def __str__(self):
        return "%s" % (self.title)

    def get_link_list(self):
        return ", ".join([p.title for p in self.links.all()])
    get_link_list.short_description = 'links'

    def get_absolute_url(self):
        link = self.links.first()
        if link:
            return link.get_absolute_url()
        return ""

maugli/menu/models.py
from django.db import models

from conf import settings

class Menu(models.Model):
    name   = models.CharField(max_length=255)
    title  = models.CharField(max_length=255, blank=True)
    def __str__(self):
        return "%s" % (self.title)

class MenuLink(models.Model):
    title  = models.CharField(max_length=255)
    url    = models.CharField(max_length=255, blank=True)
    menu   = models.ManyToManyField(Menu, blank=True, related_name="links")
    weight = models.IntegerField(default=0)
    def __str__(self):
        return "%s" % (self.title)

    def get_absolute_url(self):
        return settings.URL_ROOT+"/"+self.url

    def get_menu_list(self):
        return ", ".join([p.title for p in self.menu.all()])

    def get_entry_list(self):
        return ", ".join([p.title for p in self.entry.all()])

maugli/store/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"
    code        = models.IntegerField()
    name        = models.CharField(max_length=255, blank=True)

class AbstractColumn(models.Model):
    class Meta:
        abstract = True
    STRING  = "string"
    INT     = "int"
    DECIMAL = "decimal"
    TEXT    = "text"
    TYPE_CHOICES = (
        (STRING,  "String"),
        (INT,     "Integer"),
        (DECIMAL, "Decimal"),
        (TEXT,    "Text"),
    )
    #type        = models.CharField(max_length=255, choices=TYPE_CHOICES,
    #                                               default=STRING)

class TitleColumn(AbstractColumn):
    class Meta:
        verbose_name = 'title'
    value       = models.CharField(max_length=255, blank=True)

class PriceColumn(AbstractColumn):
    class Meta:
        verbose_name = 'price'
    value       = models.DecimalField(max_digits=20, decimal_places=2)

class Product(models.Model):
    code        = models.IntegerField()
    categories  = models.ManyToManyField(Category)
    title       = models.ForeignKey(TitleColumn, on_delete=models.CASCADE)
    price       = models.ForeignKey(PriceColumn, on_delete=models.CASCADE)
    def get_title(self):
        return self.title.value
    def get_price(self):
        return self.price.value
    def get_image_url(self):
        domain = "http://maugli-toys.com"
        return "%s/photos/%s.jpg" % (domain, self.code)

maugli/conf/views.py
from django.db import connection
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.conf import settings

from entries.models import Entry
from store.models import Product

class IndexView(TemplateView):
    template_name = "base_index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["entries"] = Entry.objects.filter(
            type=Entry.ARTICLE).order_by("date")[:10];
        context["products"] = Product.objects.all().prefetch_related(
                                                    'title',
                                                    'price',
                              )[:10];
        return context

maugli/entries/views.py
from django.http import HttpResponse
from django.conf import settings
from django.http import Http404
from django.views.generic import TemplateView

from .models import Entry
from menu.models import MenuLink

# TODO: ListView
class EntriesView(TemplateView):
    template_name = "base_entries.html"
    def get_context_data(self, **kwargs):
        context = super(EntriesView, self).get_context_data(**kwargs)
        context["entries"] = Entry.objects.order_by("-date", "-id").filter(
                                                        type=Entry.ARTICLE)
        return context

class EntryView(TemplateView):
    template_name = "base_entries_entry.html"

    def get_context_data(self, **kwargs):
        context = super(EntryView, self).get_context_data(**kwargs)
        entry_link = self.kwargs["entry_link"]
        links = MenuLink.objects.filter(url=entry_link)
        if not links:
            raise Http404
        first_link = links[0]
        entries = first_link.entry.all()
        if not entries:
            raise Http404
        context["entry"] = entries[0]
        return context

maugli/menu/views.py
from django.shortcuts import render

# Create your views here.

maugli/store/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.conf import settings

class CatalogView(TemplateView):
    template_name = "base_catalog.html"

maugli/templates/base.html
{% load menu %}
{% load staticfiles %}
{% with site_name="ООО \"Маугли\" — Лучшие игрушки в Перми" %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>{% block section-title %}{% endblock %}{{ site_name }}</title>
	<link rel="stylesheet" href="{% static "site/css/style.css" %}">
	{% block section-style %}{% endblock section-style %}
</head>
<body>
<div id="wrapper">
	<div id="head-wrapper">
	<div id="left-block"></div>
	<div id="right-block"></div>
	<div id="head">
		<div id="cart-block">
		{% block cart %}{% endblock cart %}
		</div> <!-- #cart-block -->
		<div id="profile-block">
		{% block profile %}{% endblock profile %}
		</div> <!-- #profile-block -->
	</div> <!-- #head -->
	</div> <!-- #head-wrapper -->
	<div id="navbar">
		<div class="search">&nbsp;</div>
		{% menu "nav" title="" %}
		<div class="ask">&nbsp;</div>
	</div> <!-- #navbar -->
	<div id="middle">
	<div id="left-sidebar" class="block">
	{% block left-sidebar %}
		<div class="title block top-bottom-p5">
			{% url 'store:catalog' as catalog_url %}
			<a href="{{ catalog_url }}">Каталог</a>
		</div>
	{% endblock left-sidebar %}
	</div> <!-- #left-sidebar -->
	<div class="container">
		<div id="content" {% block content-class %}{% endblock %}>
			<div class="title block top-bottom-p5">
				{#{{ section.content_title }}#}
				{% block content-title %}{% endblock %}
			</div>
			<div id="notification-area">
				{% block notify %}{% endblock notify %}
			</div> <!-- #notification-area -->
		{% block content %}{% endblock content %}
		</div> <!-- #content -->
	</div> <!-- .container -->
	{% block right-sidebar %}{% endblock right-sidebar %}
	</div> <!-- #middle -->
</div> <!-- #wrapper -->
<div id="footer">
<div class="container">
{% menu "store" %}
{% menu "company" %}
{% menu "partners" %}
{% menu "hiring" %}
{% menu "customers" %}
<div id="info">
	{% now "Y" as current_year %}
	&copy; 1993 — {{ current_year }} {{ site_name }}
	<div id="social">
		{% for link in info.social_links %}
			<a href="{{ link.url }}">
				<img src="{{ link.title }}" alt="">
			</a>
		{% endfor %}
	</div>
	<div id="made-by">
		<a href="http://ivan4b.ru">Разработка сайта: Иван Чебыкин</a>
	</div>
	<div id="stats">
		Запросов: {{ info.connection.queries|length }},
		Время загрузки: {{ load_time|floatformat:3 }}
	</div>
</div> <!-- #info -->
</div> <!-- .container -->
</div> <!-- #footer -->
</body>
</html>
{% endwith %}

maugli/templates/base_catalog.html
{% extends "base.html" %}
{% load product-list %}
{% block section-title %}
Список игрушек —
{% endblock %}
{% block content-title %}Список игрушек{% endblock %}
{% block content %}
	{% show_product_list %}
{% endblock content %}

maugli/templates/base_entries.html
{% extends "base.html" %}
{% load staticfiles %}
{% block section-style %}
	<link rel="stylesheet" href="{% static "site/css/news.css" %}">
{% endblock section-style %}
{% block section-title %} Новости — {% endblock %}
{% block content-title %} Новости {% endblock %}
{% block left-sidebar %}
	{% load menu %}
	{% menu "nav" %}
{% endblock left-sidebar %}
{% block content-class %}class="block"{% endblock %}
{% block content %}
	{% if entries %}
		{% for entry in entries %}
			<div class="block m5 entry">

			{% if entry.type == "article" %}
				<p class="date">{{ entry.date|date:"SHORT_DATE_FORMAT" }}</p>
			{% endif %}

			<h2 class="title">
				<a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
			</h2>

			<p class="text">
				{{ entry.text|safe|truncatechars:200 }}
			</p>
			</div>
		{% endfor %}
	{% else %}
	{% include "snippets/msg.html" with type="warning" text="Новостей нет" %}
	{% endif %}
{% endblock content %}

maugli/templates/base_entries_entry.html
{% extends "base_entries.html" %}
{% load staticfiles %}
{% block section-style %}
	<link rel="stylesheet" href="{% static "site/css/entries.css" %}">
{% endblock section-style %}
{% block section-title %} {{ entry.title }} — {% endblock %}
{% block content-title %} {{ entry.title }} {% endblock %}
{% block content %}
	<div class="entry">
		{% if entry.type == "article" %}
			<p class="date">{{ entry.date|date:"SHORT_DATE_FORMAT" }}</p>
		{% endif %}
		<p class="text">
			{{ entry.text|safe }}
		</p>
	</div>
{% endblock content %}

maugli/templates/base_index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load product-list %}
{% block section-style %}
<link rel="stylesheet" href="{% static "site/css/index.css" %}">
{% endblock section-style %}
{% block content-title %}Новые поступления{% endblock %}
{% block content %}
	{% show_product_list "new" %}
{% endblock content %}
{% block right-sidebar %}
<div id="right-sidebar" class="block">
	<div class="title top-bottom-p5">
		Бренды
	</div>
</div>
{% endblock right-sidebar %}

maugli/templates/snippets/menu.html
<div class="menu {{ menu.name }}">
{% if title %}
<div class="title top-bottom-p5">
	{{ title }}
</div>
{% endif %}
<ul>
{% for link in links %}
	<li>
	<a {% if url == link.url %} class="selected"
	{% endif %} href="{{ link.get_absolute_url }}">{{ link.title }}</a></li>
{% endfor %}
</ul>
</div>

maugli/templates/snippets/msg.html
<div class="notification {{ type }}">
{{ text }}
</div>

maugli/templates/snippets/product-list.html
{% load product %}
{% if products %}
	{% for p in products %}
		{% product p %}
	{% endfor %}
{% endif%}

maugli/templates/snippets/product.html
{% load humanize %}
<div class="block p10 m5 product">
	<div class="image">
	<img src="{{ product.get_image_url }}" alt="">
	</div>
	<div class="info">
		<div class="info-content">
			<div class="title p10">
				<a href="#">{{ product.get_title }}</a>
			</div>
			<div class="info-additional left-p10">
				<div class="price top-p5">
				{{ product.get_price|intcomma }} &#8381;
				</div>
				<div class="add-button"></div>
			</div>
		</div>
	</div>
</div>